name = "DNAText"
uuid = "79d3e780-ad60-11ea-3721-1dbdcb73d9a2"
authors = ["harveydevereux <harveydevereux@googlemail.com>"]
version = "0.1.0"

[deps]
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
